name: 'File Content Replacer'
description: 'Wraps replace-in-file for quick and dirty updating of project files with new build numbers, and other nafarious purposes'
inputs:
  files:
    description: "The name or glob of the file(s) to update"
    required: true
    default: '**/*.csproj'
  from:
    description: 'the value to search for in the file(s)'
    required: true
    default: '1.0.0.0'
  to:
    description: 'The value to replace in the file(s)'
    required: true
    
runs:
  using: 'node12'
  main: 'dist/index.js'
